mode: both
project: "CoPaw-Pro-RL"
group: ${oc.env:EXP_DATE}-${oc.env:EXP_SOURCE}
name: ${oc.env:EXP_NAME}
checkpoint_root_dir: ${oc.env:TRINITY_CHECKPOINT_ROOT_DIR,./checkpoints}
algorithm:
  algorithm_type: grpo
  repeat_times: 8
  optimizer:
    lr: ${oc.env:LR,1e-6}
    lr_scheduler_type: ${oc.env:LR_SCHEDULER_TYPE,cosine}
    lr_warmup_steps_ratio: ${oc.env:LR_WARMUP_STEPS_RATIO,0.05}
    min_lr_ratio: 0.1
  sample_strategy: staleness_control
  sample_strategy_args:
    max_staleness: 5
model:
  model_path: ${oc.env:MODEL_DIR,/mnt/data/chenyushuo.cys/rlhf_space/models}/${oc.env:EXP_MODEL_NAME}
  max_model_len: 262144
  enable_thinking: true
cluster:
  node_num: ${oc.env:WORLD_SIZE,1}
  gpu_per_node: ${oc.env:NPROC_PER_NODE,8}
data_processor:
  experience_pipeline:
    operators:
    - name: 'reward_std_filter_v2'
      args:
        threshold: 0.00
buffer:
  batch_size: ${oc.env:BATCH_SIZE,16}
  train_batch_size: ${oc.env:TRAIN_BATCH_SIZE,512}
  total_epochs: ${oc.env:TOTAL_EPOCHS,5}
  explorer_input:
    taskset:
      name: taskset
      storage_type: file
      path: ${oc.env:TRINITY_TASKSET_PATH,examples/copaw_rl/data}
      split: train
      format:  # TODO
        prompt_key: question
        response_key: answer
      data_selector:
        selector_type: shuffle
      workflow_args:
        token: ${oc.env:E2B_API_KEY}
        template: ${oc.env:E2B_TEMPLATE}
        domain: ${oc.env:E2B_DOMAIN,"sandbox01.vpc.cn-hongkong.pai-eas.aliyuncs.com"}
        dashscope_api_key: ${oc.env:DASHSCOPE_API_KEY}
        oss:
          access_key_id: ${oc.env:OSS_ACCESS_KEY_ID}
          access_key_secret: ${oc.env:OSS_ACCESS_KEY_SECRET}
          region: ${oc.env:OSS_REGION,cn-beijing}
          endpoint: ${oc.env:OSS_ENDPOINT,"oss-cn-beijing-internal.aliyuncs.com"}
          bucket_name: ${oc.env:OSS_BUCKET_NAME,"copaw-dataset"}
          prefix: ${oc.env:OSS_PREFIX,"data/0318_train_tasks_compressed/"}
      default_workflow_type: copaw_workflow  # examples.copaw_rl.workflows.CoPawWorkflow
    eval_tasksets: []
  trainer_input:
    experience_buffer:
      name: experience_buffer
      storage_type: queue
      max_read_timeout: 4200
      replay_buffer:
        enable: true
        # reuse_cooldown_time is None
        priority_fn: 'decay_limit_randomization'
        priority_fn_args:
          decay: 1.0
          use_count_limit: 3
          sigma: 0.5
explorer:
  runner_per_model: ${oc.env:RUNNER_PER_MODEL,32}
  max_timeout: 900
  max_retry_times: 2
  max_repeat_times_per_runner: 1
  rollout_model:
    engine_type: vllm
    engine_num: ${oc.env:ENGINE_NUM,4}
    tensor_parallel_size: 1
    use_v1: true
    enforce_eager: false
    enable_prefix_caching: true
    enable_chunked_prefill: true
    gpu_memory_utilization: 0.85
    dtype: bfloat16
    seed: 42
    enable_openai_api: true
    enable_auto_tool_choice: true
    reasoning_parser: qwen3
    tool_call_parser: qwen3_coder
  eval_interval: 10000
  over_rollout:
    ratio: 0.0
    wait_after_min: 30.0
    return_partial_tasks: ${oc.env:RETURN_PARTIAL_TASKS,false}
  bench_on_latest_checkpoint: false
synchronizer:
  sync_method: 'nccl'
  sync_interval: 1
  sync_style: "trainer_driven"
  sync_offset: 0
trainer:
  trainer_strategy: fsdp2
  total_steps: ${oc.env:TOTAL_STEPS,1000}
  save_interval: 20
  grad_clip: 1.0
  use_dynamic_bsz: ${oc.env:USE_DYNAMIC_BSZ,true}
  ulysses_sequence_parallel_size: ${oc.env:SP_SIZE,1}
  fix_actor_microbatch_loss_scale: ${oc.env:FIX_LOSS_SCALE,true}
  trainer_config:
    actor_rollout_ref:
      model:
        use_remove_padding: ${oc.env:REMOVE_PADDING,true}
        use_fused_kernels: ${oc.env:FUSED_KERNELS,true}
        fused_kernel_options:
          impl_backend: torch
monitor:
  monitor_type: wandb
