project: "ALFWORLD_TEST"
name: "v2"
checkpoint_root_dir: /mnt/yuchang/checkpoints
algorithm:
  algorithm_type: grpo
  repeat_times: 8
model:
  model_path: /mnt/checkpoint/qwen25/Qwen2.5-1.5B-Instruct
  max_prompt_tokens: 4096
  max_response_tokens: 16384
cluster:
  node_num: 1
  gpu_per_node: 8
buffer:
  total_epochs: 20
  batch_size: 32
  max_retry_times: 3
  max_retry_interval: 1
  explorer_input:
    taskset:
      name: alfworld
      storage_type: file
      path: 'examples/grpo_alfworld/alfworld_data'
      format:
        prompt_key: 'game_file'
        system_prompt: |-
          You are an agent interacting with a virtual test-based environments.

          ## Notes:
          At each step, you should first think then perform action to fulfill the instruction. You should ALWAYS wrap your thinking with the <think> </think> tag and wrap your action with the <action> </action> tag.
          You should ALWAYS take one action each step.
          DONOT try to interact with the user at anytime. Finish the task and buy the item by yourself.

          ## Action Format:
          Below are the available commands you can use:
            look:                             look around your current location
            inventory:                        check your current inventory(you can only have 1 item in your inventory)
            go to (receptacle):               move to a receptacle
            open (receptacle):                open a receptacle
            close (receptacle):               close a receptacle
            take (object) from (receptacle):  take an object from a receptacle
            move (object) to (receptacle):  place an object in or on a receptacle
            examine (something):              examine a receptacle or an object
            use (object):                     use an object
            heat (object) with (receptacle):  heat an object using a receptacle
            clean (object) with (receptacle): clean an object using a receptacle
            cool (object) with (receptacle):  cool an object using a receptacle
            slice (object) with (object):     slice an object using a sharp object

          For example your output should be like this:
          <think> To solve the task, I need first to ... </think><action>go to cabinet 1</action>
      rollout_args:
        temperature: 1.0
        logprobs: 0
    default_workflow_type: 'alfworld_workflow_v2'
  trainer_input:
    experience_buffer:
      name: alfworld_buffer
      storage_type: queue
      # path: 'sqlite:///alfworld.db'
    sft_warmup_dataset:
      name: sft_warmup_data
      storage_type: file
      path: /mnt/yuchang/datasets/alfworld/sft
      format:
        prompt_type: messages
        messages_key: messages
explorer:
  runner_num: 32
  max_timeout: 3600
  rollout_model:
    enable_history: true
    engine_type: vllm_async
    engine_num: 2
    tensor_parallel_size: 2
    enable_prefix_caching: false
    enforce_eager: true
    dtype: bfloat16
    seed: 42
    gpu_memory_utilization: 0.7
    enable_chunked_prefill: true
  env_vars:
    TMPDIR: /root/alfworld_tmp
synchronizer:
  sync_method: 'nccl'
  sync_interval: 5
  sync_timeout: 3600
trainer:
  trainer_type: 'verl'
  trainer_config_path: 'examples/grpo_alfworld/train_alfworld.yaml'
  save_interval: 10
monitor:
  monitor_type: wandb