project: "ALFWORLD_TEST"
name: "v2_step_wise_grpo_trainerBS*30"
# name: "v2_step_wise_grpo_1e-6"
checkpoint_root_dir: /mnt/yuchang/checkpoints
algorithm:
  algorithm_type: grpo
  repeat_times: 16
  # add_strategy: multi_turn
  add_strategy: step_wise_grpo
model:
  model_path: /mnt/yuchang/checkpoints/alfworld_sft
  max_prompt_tokens: 4096
  max_response_tokens: 16384
cluster:
  node_num: 1
  gpu_per_node: 8
buffer:
  total_epochs: 15
  batch_size: 16
  max_retry_times: 3
  max_retry_interval: 1
  explorer_input:
    taskset:
      name: alfworld
      storage_type: file
      path: 'examples/grpo_alfworld/alfworld_data'
      format:
        prompt_key: 'game_file'
      rollout_args:
        temperature: 1.0
        logprobs: 0
      enable_progress_bar: false
      workflow_args:
        max_env_steps: 30
    default_workflow_type: 'alfworld_workflow_v2'
  trainer_input:
    experience_buffer:
      name: alfworld_buffer
      storage_type: queue
      use_priority_queue: true
      replay_buffer_kwargs:
        priority_fn: linear_decay
        decay: 0.1
explorer:
  max_repeat_times_per_runner: 1
  max_timeout: 3600
  rollout_model:
    enable_history: true
    engine_type: vllm_async
    engine_num: 2
    tensor_parallel_size: 2
    enable_prefix_caching: false
    enforce_eager: true
    dtype: bfloat16
    seed: 42
    gpu_memory_utilization: 0.7
    enable_chunked_prefill: true
  env_vars:
    TMPDIR: /root/alfworld_tmp
synchronizer:
  sync_style: dynamic_by_explorer
  sync_method: 'nccl'
  sync_interval: 2
  sync_timeout: 3600
trainer:
  trainer_type: 'verl'
  trainer_config_path: 'examples/grpo_alfworld/train_alfworld.yaml'
  save_interval: 50
monitor:
  monitor_type: wandb