project: "rft_sft_mixed"
name: "openr1_only_rft"
checkpoint_root_dir: /mnt/data/yuchang/checkpoints/
algorithm:
  algorithm_type: grpo
  repeat_times: 8
model:
  model_path: /cpfs/data/xielipeng.xlp/models/Qwen2.5-7B-Instruct
  max_prompt_tokens: 1024
  max_response_tokens: 16392
cluster:
  node_num: 1
  gpu_per_node: 8
buffer:
  total_epochs: 1
  batch_size: 64
  max_retry_times: 3
  max_retry_interval: 1
  explorer_input:
    taskset:
      name: openr1
      storage_type: file
      path: /cpfs/data/zhangwenhao.zwh/sftp/Trinity-RFT/scripts/data_prepare/openr1_data_filtered_int
      split: 'train'
      format:
        prompt_key: 'problem'
        response_key: 'answer'
      rollout_args:
        n: 8
        temperature: 1.0
        logprobs: 0
    eval_tasksets:
    - name: openr1
      storage_type: file
      path: /cpfs/data/zhangwenhao.zwh/sftp/Trinity-RFT/scripts/data_prepare/openr1_data_filtered_int
      split: 'test'
      format:
        prompt_key: 'problem'
        response_key: 'answer'
    default_workflow_type: 'math_r1_workflow'
  trainer_input:
    experience_buffer:
      name: openr1_buffer
      storage_type: queue
      path: 'sqlite:////mnt/data/yuchang/checkpoints/${project}/${name}/openr1.db'
    sft_warmup_steps: 0
explorer:
  eval_interval: 10
  runner_num: 32
  rollout_model:
    engine_type: vllm_async
    engine_num: 4
    tensor_parallel_size: 1
    enable_prefix_caching: false
    enforce_eager: true
    dtype: bfloat16
    seed: 42
synchronizer:
  sync_method: 'nccl'
  sync_interval: 1
  sync_timeout: 1200
trainer:
  trainer_type: 'verl'
  trainer_config_path: 'examples/grpo_math/train_math.yaml'
  save_interval: 50
