project: "Trinity-RFT-tir-MATH"
name: "Curriculum-Qwen3-4B-trained-TIR_v2_test_dlc_200step_2node_only_train_success_nokl"
checkpoint_root_dir: /mnt/data/yuchang/checkpoints
algorithm:
  algorithm_type: multi_step_grpo
  repeat_times: 16
  # advantage_fn_args:
  #   std_threshold: 0.0001
  policy_loss_fn: ppo
  policy_loss_fn_args:
    clip_range_low: 0.2
    clip_range_high: 0.28
  kl_loss_fn_args:
    kl_coef: 0.0
  optimizer:
    lr: 2e-6
model:
  model_path: /mnt/data/zhangwenhao.zwh/checkpoints/Trinity-Tir-STEM/sft_math_tir_v1_test/global_step_200/actor/huggingface
  max_response_tokens: 20000
  min_response_tokens: 0
  max_model_len: 64000
cluster:
  node_num: 2
  gpu_per_node: 8
buffer:
  total_epochs: 4
  batch_size: 32
  train_batch_size: 1024
  explorer_input:
    tasksets:
      - name: math
        storage_type: file
        path: /cpfs/data/tir/data/filter_all_correct/math
        split: train
        format:
          prompt_key: 'question'
          response_key: 'answer'
        reward_fn_args:
          setup: "all_llm_judge"
        task_selector:
          selector_type: offline_curriculum
          feature_keys: ["avg@8_qwen3_4b_instruct_2507"] 
    eval_tasksets:
      - name: AIME2024
        storage_type: file
        path: /mnt/data/yuchang/datasets/AIME24
        split: test
        repeat_times: 32
        format:
          prompt_key: 'problem'
          response_key: 'answer'
        rollout_args:
          temperature: 0.7
          top_p: 0.8
      - name: AIME2025
        storage_type: file
        path: /mnt/data/yuchang/datasets/AIME25
        split: test
        repeat_times: 32
        format:
          prompt_key: 'problem'
          response_key: 'answer'
        rollout_args:
          temperature: 0.7
          top_p: 0.8
    default_workflow_type: 'math_tool_integrated_reasoning_workflow_v1'
  trainer_input:
    experience_buffer:
      name: math_tir_buffer
      storage_type: queue
      max_read_timeout: 6400
explorer:
  max_repeat_times_per_runner: 1
  eval_interval: 20
  runner_per_model: 32
  max_timeout: 3600
  rollout_model:
    engine_num: 8
    tensor_parallel_size: 1
    enable_prefix_caching: false
    enforce_eager: true
    enable_openai_api: true
    enable_history: true
    dtype: bfloat16
    seed: 42
    enable_auto_tool_choice: true
    tool_call_parser: hermes
  over_rollout:
    ratio: 0.1
    wait_after_min: 120
synchronizer:
  sync_style: dynamic_by_explorer
  sync_method: 'nccl'
  sync_interval: 4
  sync_timeout: 72000
trainer:
  save_interval: 100
  grad_clip: 1.0
  use_dynamic_bsz: true
  max_token_len_per_gpu: 17000
  ulysses_sequence_parallel_size: 4
# monitor:
#   monitor_type: wandb
