continue_from_checkpoint: false
project: "trinity_tir_stem"
name: "cispo-math-qwen25-3b"
checkpoint_root_dir: /mnt/data/yuchang/checkpoints
algorithm:
  algorithm_type: cispo
  repeat_times: 16
  optimizer:
    lr: 1e-6
  policy_loss_fn_args:
    clip_range_low: 0.2
    clip_range_high: 0.28
  kl_loss_fn_args:
    kl_coef: 0.0
model:
  model_path: /cpfs/data/shared/qwen/Qwen2.5-3B-Instruct
  enable_prompt_truncation: false
  max_prompt_tokens: 4096
  max_response_tokens: 28672
  temperature: 0.7
cluster:
  node_num: 1
  gpu_per_node: 8
buffer:
  total_epochs: 5
  batch_size: 32
  explorer_input:
    tasksets:
      - name: math
        storage_type: file
        path: /cpfs/data/tir/data/filter_all_correct/math
        split: train
        format:
          prompt_key: 'question'
          response_key: 'answer'
        reward_fn_args:
          setup: "all_rule_based"
        task_selector:
          selector_type: random
    eval_tasksets:
      - name: AIME2024
        storage_type: file
        path: /mnt/data/yuchang/datasets/AIME24
        split: test
        repeat_times: 32
        format:
          prompt_key: 'problem'
          response_key: 'answer'
        rollout_args:
          temperature: 0.7
          top_p: 0.8
        reward_fn_args:
          setup: "all_rule_based"
      # - name: AIME2025
      #   storage_type: file
      #   path: /mnt/data/yuchang/datasets/AIME25
      #   repeat_times: 32
      #   split: test
      #   format:
      #     prompt_key: 'problem'
      #     response_key: 'answer'
      #   rollout_args:
      #     temperature: 0.7
      #     top_p: 0.8
      #   reward_fn_args:
      #     setup: "all_rule_based"
      # - name: GPQA_main
      #   storage_type: file
      #   path: /cpfs/data/tir/data/gpqa/main
      #   split: train
      #   repeat_times: 4
      #   format:
      #     prompt_key: 'question'
      #     response_key: 'answer'
      #   rollout_args:
      #     temperature: 0.7
      #     top_p: 0.8
      #   reward_fn_args:
      #     setup: "all_llm_judge"
      # - name: GPQA_diamond
      #   storage_type: file
      #   path: /cpfs/data/tir/data/gpqa/diamond
      #   split: train
      #   repeat_times: 4
      #   format:
      #     prompt_key: 'question'
      #     response_key: 'answer'
      #   rollout_args:
      #     temperature: 0.7
      #     top_p: 0.8
      #   reward_fn_args:
      #     setup: "all_llm_judge"
    default_workflow_type: 'async_math_boxed_workflow_v2'
explorer:
  eval_on_startup: true
  eval_interval: 20
  runner_per_model: 8
  rollout_model:
    engine_num: 4
    tensor_parallel_size: 1
    enable_chunked_prefill: true
    enforce_eager: false
    dtype: bfloat16
    seed: 42
    gpu_memory_utilization: 0.85
  # auxiliary_models:
  #   - model_path: /cpfs/data/tir/model/CompassVerifier-3B
  #     engine_num: 1
  #     tensor_parallel_size: 2
  #     max_prompt_tokens: 33368 # 32684+600
  #     max_response_tokens: 100
trainer:
  enable_preview: false
  trainer_type: 'verl'
  save_interval: 100
  use_dynamic_bsz: true
  max_token_len_per_gpu: 16384
  ulysses_sequence_parallel_size: 2
synchronizer:
  sync_method: nccl
  sync_interval: 4
  sync_timeout: 3600
monitor:
  monitor_type: wandb
